Adding typed operations related functionalities
Metronlab/bow pull request #24
Opened 2021-01-22 15:37 UTC by Pikipoo

2021-02-04 16:43 UTC, agelloz approved these changes

2021-02-04 16:43 UTC, agelloz commented on bow.go
> +	FindFirst(colIndex int, value interface{}) int
```suggestion
	FindFirst(colIndex int, value interface{}) (rowIndex int)
```
to improve clarity

2021-02-04 16:43 UTC, agelloz commented on bowgetters.go
> +}
```suggestion
func (b *bow) FindFirst(colIndex int, value interface{}) (rowIndex int) {
	valueToFind := b.GetType(colIndex).Convert(value)

	for row := 0; row < b.NumRows(); {
		rowValue, rowIndex := b.GetNextValue(colIndex, row)
		if rowIndex == -1 || rowValue == valueToFind {
			return
		}
		row = rowIndex + 1
	}
	return -1
}
```

2021-02-04 16:43 UTC, agelloz commented on bowgetters.go
> +}
I find it easier to understand :)

2021-02-05 02:50 UTC, nyhu requested changes

2021-02-10 08:38 UTC, agelloz approved these changes

2021-02-11 15:59 UTC, nyhu approved these changes

2021-02-12 17:25 UTC, merged